import { TossinvestError } from "./errors.ts";

// 공식 canonical JSON 1.2.24에서 추출한 계약이다. 등록 여부와 계약 존재를 구분한다.
export const CONTRACT_SOURCE = "https://openapi.tossinvest.com/openapi-docs/latest/openapi.json";
export const CONTRACT_SHA256 = "7e753c21dc4b938d8f9610ce3efd6542783018977cb030e39db5a006f5b59d40";
export interface Operation { id: string; method: string; path: string; group: string; input: any; responses: Record<string, any> }
export const OPERATIONS: readonly Operation[] = [
  {"id":"issueOAuth2Token","method":"POST","path":"/oauth2/token","group":"AUTH","input":{"body":{"$ref":"#/components/schemas/OAuth2TokenRequest"}},"responses":{"200":{"$ref":"#/components/schemas/OAuth2TokenResponse"},"400":{"$ref":"#/components/schemas/OAuth2ErrorResponse"},"401":{"$ref":"#/components/schemas/OAuth2ErrorResponse"},"403":{"$ref":"#/components/schemas/OAuth2ErrorResponse"},"429":{}}},
  {"id":"getOrderbook","method":"GET","path":"/api/v1/orderbook","group":"MARKET_DATA","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/OrderbookResponse"}}}]},"404":{},"429":{},"500":{}}},
  {"id":"getPrices","method":"GET","path":"/api/v1/prices","group":"MARKET_DATA","input":{"symbols":{"type":"string","pattern":"^[A-Za-z0-9.,\\-]+$"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/PriceResponse"}}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{},"429":{},"500":{}}},
  {"id":"getTrades","method":"GET","path":"/api/v1/trades","group":"MARKET_DATA","input":{"count":{"type":"integer","minimum":1,"maximum":50}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/Trade"}}}}]},"404":{},"429":{},"500":{}}},
  {"id":"getPriceLimit","method":"GET","path":"/api/v1/price-limits","group":"MARKET_DATA","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/PriceLimitResponse"}}}]},"404":{},"429":{},"500":{}}},
  {"id":"getCandles","method":"GET","path":"/api/v1/candles","group":"MARKET_DATA_CHART","input":{"interval":{"type":"string"},"count":{"type":"integer","minimum":1,"maximum":200},"before":{"type":"string","format":"date-time"},"adjusted":{"type":"boolean"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/CandlePageResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{},"429":{},"500":{}}},
  {"id":"getStocks","method":"GET","path":"/api/v1/stocks","group":"STOCK","input":{"symbols":{"type":"string","pattern":"^[A-Za-z0-9.,\\-]+$"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/StockInfo"}}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"429":{},"500":{}}},
  {"id":"listStocks","method":"GET","path":"/api/v1/stocks/all","group":"STOCK_ALL","input":{"market":{"type":"string"},"status":{"type":"string"},"securityType":{"type":"string"},"commonShare":{"type":"boolean"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/ListedStock"}}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"429":{},"500":{}}},
  {"id":"getStockWarnings","method":"GET","path":"/api/v1/stocks/{symbol}/warnings","group":"STOCK","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/StockWarning"}}}}]},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getStockInvestorTrading","method":"GET","path":"/api/v1/stocks/{symbol}/investor-trading","group":"STOCK_TRADING_TREND","input":{"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/StockInvestorTradingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getStockProgramTrades","method":"GET","path":"/api/v1/stocks/{symbol}/program-trades","group":"STOCK_TRADING_TREND","input":{"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ProgramTradesResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getStockShortSelling","method":"GET","path":"/api/v1/stocks/{symbol}/short-selling","group":"STOCK_TRADING_TREND","input":{"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ShortSellingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getStockCreditTrades","method":"GET","path":"/api/v1/stocks/{symbol}/credit-trades","group":"STOCK_TRADING_TREND","input":{"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/CreditTradesResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getStockSecuritiesLending","method":"GET","path":"/api/v1/stocks/{symbol}/securities-lending","group":"STOCK_TRADING_TREND","input":{"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SecuritiesLendingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"403":{},"404":{},"429":{},"500":{}}},
  {"id":"getExchangeRate","method":"GET","path":"/api/v1/exchange-rate","group":"MARKET_INFO","input":{"dateTime":{"type":"string","format":"date-time"},"baseCurrency":{"$ref":"#/components/schemas/Currency"},"quoteCurrency":{"$ref":"#/components/schemas/Currency"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ExchangeRateResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getKrMarketCalendar","method":"GET","path":"/api/v1/market-calendar/KR","group":"MARKET_INFO","input":{"date":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/KrMarketCalendarResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getUsMarketCalendar","method":"GET","path":"/api/v1/market-calendar/US","group":"MARKET_INFO","input":{"date":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/UsMarketCalendarResponse"}}}]},"429":{},"500":{}}},
  {"id":"getRankings","method":"GET","path":"/api/v1/rankings","group":"RANKING","input":{"type":{"type":"string"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"},"duration":{"type":"string"},"excludeInvestmentCaution":{"type":"boolean"},"count":{"type":"integer","minimum":1,"maximum":100}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/RankingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getMarketIndicatorPrices","method":"GET","path":"/api/v1/market-indicators/prices","group":"MARKET_INDICATOR","input":{"symbols":{"type":"string","pattern":"^[A-Za-z0-9_,]+$"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/MarketIndicatorPriceResponse"}}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getMarketIndicatorCandles","method":"GET","path":"/api/v1/market-indicators/{symbol}/candles","group":"MARKET_INDICATOR_CHART","input":{"symbol":{"type":"string","pattern":"^[A-Za-z0-9_]+$"},"interval":{"type":"string"},"count":{"type":"integer","minimum":1,"maximum":200},"before":{"type":"string","format":"date-time"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/MarketIndicatorCandlePageResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getMarketIndicatorInvestorTrading","method":"GET","path":"/api/v1/market-indicators/{symbol}/investor-trading","group":"MARKET_INDICATOR","input":{"symbol":{"type":"string"},"interval":{"type":"string"},"count":{"type":"integer","minimum":1,"maximum":100},"until":{"type":"string","format":"date"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/InvestorTradingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"listSectors","method":"GET","path":"/api/v1/sectors","group":"SECTOR","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SectorsResponse"}}}]},"429":{},"500":{}}},
  {"id":"getSectorRankings","method":"GET","path":"/api/v1/sectors/rankings","group":"SECTOR_RANKING","input":{"type":{"type":"string"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"},"duration":{"type":"string"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SectorRankingResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getSector","method":"GET","path":"/api/v1/sectors/{sectorId}","group":"SECTOR","input":{"sectorId":{"type":"string","pattern":"^[A-Za-z0-9_-]{1,40}$"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SectorDetailResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{},"429":{},"500":{}}},
  {"id":"getSectorStocks","method":"GET","path":"/api/v1/sectors/{sectorId}/stocks","group":"SECTOR","input":{"sectorId":{"type":"string","pattern":"^[A-Za-z0-9_-]{1,40}$"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SectorStocksResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{},"429":{},"500":{}}},
  {"id":"getSectorEtfs","method":"GET","path":"/api/v1/sectors/{sectorId}/etfs","group":"SECTOR","input":{"sectorId":{"type":"string","pattern":"^[A-Za-z0-9_-]{1,40}$"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SectorEtfsResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{},"429":{},"500":{}}},
  {"id":"getAccounts","method":"GET","path":"/api/v1/accounts","group":"ACCOUNT","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/Account"}}}}]},"401":{},"429":{},"500":{}}},
  {"id":"getHoldings","method":"GET","path":"/api/v1/holdings","group":"ASSET","input":{"symbol":{"type":"string","pattern":"^[A-Za-z0-9.\\-]+$"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/HoldingsOverview"}}}]},"400":{},"401":{},"404":{},"429":{},"500":{}}},
  {"id":"getOrders","method":"GET","path":"/api/v1/orders","group":"ORDER_HISTORY","input":{"status":{"type":"string"},"symbol":{"type":"string","pattern":"^[A-Za-z0-9.\\-]+$"},"from":{"type":"string","format":"date"},"to":{"type":"string","format":"date"},"cursor":{"type":"string"},"limit":{"type":"integer","minimum":1,"maximum":100}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/PaginatedOrderResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"404":{},"429":{},"500":{}}},
  {"id":"createOrder","method":"POST","path":"/api/v1/orders","group":"ORDER","input":{"body":{"$ref":"#/components/schemas/OrderCreateRequest"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/OrderResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"409":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"getOrder","method":"GET","path":"/api/v1/orders/{orderId}","group":"ORDER_HISTORY","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/Order"}}}]},"400":{},"401":{},"404":{},"429":{},"500":{}}},
  {"id":"modifyOrder","method":"POST","path":"/api/v1/orders/{orderId}/modify","group":"ORDER","input":{"body":{"$ref":"#/components/schemas/OrderModifyRequest"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/OrderOperationResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"404":{"$ref":"#/components/schemas/ErrorResponse"},"409":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"cancelOrder","method":"POST","path":"/api/v1/orders/{orderId}/cancel","group":"ORDER","input":{"body":{"type":"object"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/OrderOperationResponse"}}}]},"400":{},"401":{},"404":{},"409":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"createConditionalOrder","method":"POST","path":"/api/v1/conditional-orders","group":"CONDITIONAL_ORDER","input":{"body":{"$ref":"#/components/schemas/ConditionalOrderCreateRequest"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ConditionalOrderCreateResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"getConditionalOrders","method":"GET","path":"/api/v1/conditional-orders","group":"CONDITIONAL_ORDER_HISTORY","input":{"status":{"type":"string"},"symbol":{"type":"string","pattern":"^[A-Za-z0-9.\\-]+$"},"cursor":{"type":"string","pattern":"^[A-Za-z0-9_\\-]+$"},"limit":{"type":"integer","minimum":1,"maximum":100}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/PaginatedConditionalOrderResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"getConditionalOrder","method":"GET","path":"/api/v1/conditional-orders/{conditionalOrderId}","group":"CONDITIONAL_ORDER_HISTORY","input":{"conditionalOrderId":{"type":"string"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ConditionalOrderDetailResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"cancelConditionalOrder","method":"DELETE","path":"/api/v1/conditional-orders/{conditionalOrderId}","group":"CONDITIONAL_ORDER","input":{"conditionalOrderId":{"type":"string"}},"responses":{"204":{},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"modifyConditionalOrder","method":"POST","path":"/api/v1/conditional-orders/{conditionalOrderId}/modify","group":"CONDITIONAL_ORDER","input":{"conditionalOrderId":{"type":"string"},"body":{"$ref":"#/components/schemas/ConditionalOrderModifyRequest"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/ConditionalOrderResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"404":{"$ref":"#/components/schemas/ErrorResponse"},"422":{"$ref":"#/components/schemas/ErrorResponse"}}},
  {"id":"getBuyingPower","method":"GET","path":"/api/v1/buying-power","group":"ORDER_INFO","input":{"currency":{"$ref":"#/components/schemas/Currency"}},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/BuyingPowerResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"404":{"$ref":"#/components/schemas/ErrorResponse"},"429":{},"500":{}}},
  {"id":"getSellableQuantity","method":"GET","path":"/api/v1/sellable-quantity","group":"ORDER_INFO","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"$ref":"#/components/schemas/SellableQuantityResponse"}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"404":{},"429":{},"500":{}}},
  {"id":"getCommissions","method":"GET","path":"/api/v1/commissions","group":"ORDER_INFO","input":{},"responses":{"200":{"allOf":[{"$ref":"#/components/schemas/ApiResponse"},{"type":"object","properties":{"result":{"type":"array","items":{"$ref":"#/components/schemas/Commission"}}}}]},"400":{"$ref":"#/components/schemas/ErrorResponse"},"401":{},"429":{},"500":{}}},
];
export const SCHEMAS: Record<string, any> = {
  "ApiResponse": {"type":"object","required":["result"],"properties":{"result":{}}},
  "ErrorResponse": {"type":"object","required":["error"],"properties":{"error":{"$ref":"#/components/schemas/ApiError"}}},
  "ApiError": {"type":"object","required":["requestId","code","message"],"properties":{"requestId":{"type":"string"},"code":{"type":"string"},"message":{"type":"string"},"data":{"type":["object","null"]}}},
  "Currency": {"type":"string"},
  "MarketCountry": {"type":"string"},
  "OAuth2TokenRequest": {"type":"object","required":["grant_type","client_id","client_secret"],"properties":{"grant_type":{"type":"string"},"client_id":{"type":"string"},"client_secret":{"type":"string","format":"password"}}},
  "OAuth2TokenResponse": {"type":"object","required":["access_token","token_type","expires_in"],"properties":{"access_token":{"type":"string"},"token_type":{"type":"string"},"expires_in":{"type":"integer","format":"int64"}}},
  "OAuth2ErrorResponse": {"type":"object","required":["error"],"properties":{"error":{"type":"string"},"error_description":{"type":"string"},"error_uri":{"type":"string","format":"uri"}}},
  "OrderbookEntry": {"type":"object","required":["price","volume"],"properties":{"price":{"type":"string","format":"decimal","maxLength":30},"volume":{"type":"string","format":"decimal","maxLength":30}}},
  "OrderbookResponse": {"type":"object","required":["currency","asks","bids"],"properties":{"timestamp":{"type":["string","null"],"format":"date-time"},"currency":{"$ref":"#/components/schemas/Currency"},"asks":{"type":"array","items":{"$ref":"#/components/schemas/OrderbookEntry"}},"bids":{"type":"array","items":{"$ref":"#/components/schemas/OrderbookEntry"}}}},
  "PriceResponse": {"type":"object","required":["symbol","lastPrice","currency"],"properties":{"symbol":{"type":"string"},"timestamp":{"type":["string","null"],"format":"date-time"},"lastPrice":{"type":"string","format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "Trade": {"type":"object","required":["price","volume","timestamp","currency"],"properties":{"price":{"type":"string","format":"decimal","maxLength":30},"volume":{"type":"string","format":"decimal","maxLength":30},"timestamp":{"type":"string","format":"date-time"},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "PriceLimitResponse": {"type":"object","required":["timestamp","currency"],"properties":{"timestamp":{"type":"string","format":"date-time"},"upperLimitPrice":{"type":["string","null"],"format":"decimal","maxLength":30},"lowerLimitPrice":{"type":["string","null"],"format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "CandlePageResponse": {"type":"object","required":["candles"],"properties":{"candles":{"type":"array","items":{"$ref":"#/components/schemas/Candle"}},"nextBefore":{"type":["string","null"],"format":"date-time"}}},
  "Candle": {"type":"object","required":["timestamp","openPrice","highPrice","lowPrice","closePrice","volume","currency"],"properties":{"timestamp":{"type":"string","format":"date-time"},"openPrice":{"type":"string","format":"decimal","maxLength":30},"highPrice":{"type":"string","format":"decimal","maxLength":30},"lowPrice":{"type":"string","format":"decimal","maxLength":30},"closePrice":{"type":"string","format":"decimal","maxLength":30},"volume":{"type":"string","format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "StockInfo": {"type":"object","required":["symbol","name","englishName","isinCode","market","securityType","isCommonShare","status","currency","sharesOutstanding"],"properties":{"symbol":{"type":"string"},"name":{"type":"string"},"englishName":{"type":"string"},"isinCode":{"type":"string"},"market":{"type":"string"},"securityType":{"type":"string"},"isCommonShare":{"type":"boolean"},"status":{"type":"string"},"currency":{"$ref":"#/components/schemas/Currency"},"listDate":{"type":["string","null"],"format":"date"},"delistDate":{"type":["string","null"],"format":"date"},"sharesOutstanding":{"type":"string","format":"decimal","maxLength":30},"leverageFactor":{"type":["string","null"],"format":"decimal","maxLength":30},"koreanMarketDetail":{"oneOf":[{"$ref":"#/components/schemas/KrMarketDetail"},{"type":"null"}]}}},
  "KrMarketDetail": {"type":"object","required":["liquidationTrading","nxtSupported","krxTradingSuspended"],"properties":{"liquidationTrading":{"type":"boolean"},"nxtSupported":{"type":"boolean"},"krxTradingSuspended":{"type":"boolean"},"nxtTradingSuspended":{"type":["boolean","null"]}}},
  "StockWarning": {"type":"object","required":["warningType"],"properties":{"warningType":{"type":"string"},"exchange":{"type":["string","null"]},"startDate":{"type":["string","null"],"format":"date"},"endDate":{"type":["string","null"],"format":"date"}}},
  "ListedStock": {"type":"object","required":["symbol","name","securityType","isCommonShare","isinCode"],"properties":{"symbol":{"type":"string"},"name":{"type":"string"},"securityType":{"type":"string"},"isCommonShare":{"type":"boolean"},"isinCode":{"type":"string"}}},
  "StockInvestorTradingResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/StockInvestorTradingRecord"}}}},
  "StockInvestorTradingRecord": {"type":"object","required":["date","updatedAt","foreigner","institution"],"properties":{"date":{"type":"string","format":"date"},"updatedAt":{"type":"string","format":"date-time"},"individual":{"oneOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"},{"type":"null"}]},"foreigner":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"institution":{"allOf":[{"$ref":"#/components/schemas/StockInstitutionTradingVolume"}]},"otherCorporation":{"oneOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"},{"type":"null"}]},"foreignerHolding":{"oneOf":[{"$ref":"#/components/schemas/ForeignerHolding"},{"type":"null"}]},"cfd":{"oneOf":[{"$ref":"#/components/schemas/CfdBalance"},{"type":"null"}]}}},
  "InvestorTradingVolume": {"type":"object","required":["buyVolume","sellVolume","netBuyVolume"],"properties":{"buyVolume":{"type":"string","format":"decimal","maxLength":30},"sellVolume":{"type":"string","format":"decimal","maxLength":30},"netBuyVolume":{"type":"string","format":"decimal","maxLength":30}}},
  "StockInstitutionTradingVolume": {"type":"object","required":["buyVolume","sellVolume","netBuyVolume"],"properties":{"buyVolume":{"type":"string","format":"decimal","maxLength":30},"sellVolume":{"type":"string","format":"decimal","maxLength":30},"netBuyVolume":{"type":"string","format":"decimal","maxLength":30},"breakdown":{"oneOf":[{"$ref":"#/components/schemas/StockInstitutionTradingBreakdown"},{"type":"null"}]}}},
  "StockInstitutionTradingBreakdown": {"type":"object","required":["financialInvestment","insurance","trust","privateEquityFund","bank","otherFinancialInstitution","pensionFund"],"properties":{"financialInvestment":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"insurance":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"trust":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"privateEquityFund":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"bank":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"otherFinancialInstitution":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]},"pensionFund":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingVolume"}]}}},
  "ForeignerHolding": {"type":"object","required":["holdingQuantity","limitQuantity","holdingRate"],"properties":{"holdingQuantity":{"type":"string","format":"decimal","maxLength":30},"limitQuantity":{"type":"string","format":"decimal","maxLength":30},"holdingRate":{"type":"string","format":"decimal","maxLength":30}}},
  "CfdBalance": {"type":"object","required":["buyBalanceQuantity","buyBalanceRate","sellBalanceQuantity","sellBalanceRate"],"properties":{"buyBalanceQuantity":{"type":"string","format":"decimal","maxLength":30},"buyBalanceRate":{"type":"string","format":"decimal","maxLength":30},"sellBalanceQuantity":{"type":"string","format":"decimal","maxLength":30},"sellBalanceRate":{"type":"string","format":"decimal","maxLength":30}}},
  "ProgramTradesResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/ProgramTradeRecord"}}}},
  "ProgramTradeRecord": {"type":"object","required":["date","arbitrage","nonArbitrage"],"properties":{"date":{"type":"string","format":"date"},"arbitrage":{"allOf":[{"$ref":"#/components/schemas/ProgramTradingVolume"}]},"nonArbitrage":{"allOf":[{"$ref":"#/components/schemas/ProgramTradingVolume"}]}}},
  "ProgramTradingVolume": {"type":"object","required":["buyVolume","sellVolume","netBuyVolume"],"properties":{"buyVolume":{"type":"string","format":"decimal","maxLength":30},"sellVolume":{"type":"string","format":"decimal","maxLength":30},"netBuyVolume":{"type":"string","format":"decimal","maxLength":30}}},
  "ShortSellingResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/ShortSellingRecord"}}}},
  "ShortSellingRecord": {"type":"object","required":["date","updatedAt","shortSellingVolume","shortSellingAmount"],"properties":{"date":{"type":"string","format":"date"},"updatedAt":{"type":"string","format":"date-time"},"shortSellingVolume":{"type":"string","format":"decimal","maxLength":30},"shortSellingAmount":{"type":"string","format":"decimal","maxLength":30},"shortSellingVolumeRate":{"type":["string","null"],"format":"decimal","maxLength":30},"shortSellingAmountRate":{"type":["string","null"],"format":"decimal","maxLength":30}}},
  "CreditTradesResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/CreditTradeRecord"}}}},
  "CreditTradeRecord": {"type":"object","required":["date","updatedAt"],"properties":{"date":{"type":"string","format":"date"},"updatedAt":{"type":"string","format":"date-time"},"marginLoan":{"oneOf":[{"$ref":"#/components/schemas/CreditTradeDetail"},{"type":"null"}]},"stockLoan":{"oneOf":[{"$ref":"#/components/schemas/CreditTradeDetail"},{"type":"null"}]}}},
  "CreditTradeDetail": {"type":"object","required":["newQuantity","returnQuantity","balanceQuantity","balanceRate","tradingRate"],"properties":{"newQuantity":{"type":"string","format":"decimal","maxLength":30},"returnQuantity":{"type":"string","format":"decimal","maxLength":30},"balanceQuantity":{"type":"string","format":"decimal","maxLength":30},"balanceRate":{"type":"string","format":"decimal","maxLength":30},"tradingRate":{"type":"string","format":"decimal","maxLength":30}}},
  "SecuritiesLendingResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/SecuritiesLendingRecord"}}}},
  "SecuritiesLendingRecord": {"type":"object","required":["date","updatedAt","executionQuantity","repaymentQuantity","balanceQuantity","balanceAmount"],"properties":{"date":{"type":"string","format":"date"},"updatedAt":{"type":"string","format":"date-time"},"executionQuantity":{"type":"string","format":"decimal","maxLength":30},"repaymentQuantity":{"type":"string","format":"decimal","maxLength":30},"balanceQuantity":{"type":"string","format":"decimal","maxLength":30},"balanceAmount":{"type":"string","format":"decimal","maxLength":30}}},
  "ExchangeRateResponse": {"type":"object","required":["baseCurrency","quoteCurrency","rate","midRate","basisPoint","rateChangeType","validFrom","validUntil"],"properties":{"baseCurrency":{"$ref":"#/components/schemas/Currency"},"quoteCurrency":{"$ref":"#/components/schemas/Currency"},"rate":{"type":"string","format":"decimal","maxLength":30},"midRate":{"type":"string","format":"decimal","maxLength":30},"basisPoint":{"type":"string","format":"decimal","maxLength":30},"rateChangeType":{"type":"string"},"validFrom":{"type":"string","format":"date-time"},"validUntil":{"type":"string","format":"date-time"}}},
  "KrMarketCalendarResponse": {"type":"object","required":["today","previousBusinessDay","nextBusinessDay"],"properties":{"today":{"$ref":"#/components/schemas/KrMarketDay"},"previousBusinessDay":{"$ref":"#/components/schemas/KrMarketDay"},"nextBusinessDay":{"$ref":"#/components/schemas/KrMarketDay"}}},
  "KrMarketDay": {"type":"object","required":["date"],"properties":{"date":{"type":"string","format":"date"},"integrated":{"oneOf":[{"$ref":"#/components/schemas/IntegratedHour"},{"type":"null"}]}}},
  "IntegratedHour": {"type":"object","properties":{"preMarket":{"oneOf":[{"$ref":"#/components/schemas/PreMarketSession"},{"type":"null"}]},"regularMarket":{"oneOf":[{"$ref":"#/components/schemas/RegularMarketSession"},{"type":"null"}]},"afterMarket":{"oneOf":[{"$ref":"#/components/schemas/AfterMarketSession"},{"type":"null"}]}}},
  "PreMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"singlePriceAuctionStartTime":{"oneOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"endTime":{"type":"string","format":"date-time"}}},
  "RegularMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"singlePriceAuctionStartTime":{"oneOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"endTime":{"type":"string","format":"date-time"}}},
  "AfterMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"singlePriceAuctionEndTime":{"oneOf":[{"type":"string","format":"date-time"},{"type":"null"}]},"endTime":{"type":"string","format":"date-time"}}},
  "UsMarketCalendarResponse": {"type":"object","required":["today","previousBusinessDay","nextBusinessDay"],"properties":{"today":{"$ref":"#/components/schemas/UsMarketDay"},"previousBusinessDay":{"$ref":"#/components/schemas/UsMarketDay"},"nextBusinessDay":{"$ref":"#/components/schemas/UsMarketDay"}}},
  "UsMarketDay": {"type":"object","required":["date"],"properties":{"date":{"type":"string","format":"date"},"dayMarket":{"oneOf":[{"$ref":"#/components/schemas/UsDayMarketSession"},{"type":"null"}]},"preMarket":{"oneOf":[{"$ref":"#/components/schemas/UsPreMarketSession"},{"type":"null"}]},"regularMarket":{"oneOf":[{"$ref":"#/components/schemas/UsRegularMarketSession"},{"type":"null"}]},"afterMarket":{"oneOf":[{"$ref":"#/components/schemas/UsAfterMarketSession"},{"type":"null"}]}}},
  "UsDayMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"endTime":{"type":"string","format":"date-time"}}},
  "UsPreMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"endTime":{"type":"string","format":"date-time"}}},
  "UsRegularMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"endTime":{"type":"string","format":"date-time"}}},
  "UsAfterMarketSession": {"type":"object","required":["startTime","endTime"],"properties":{"startTime":{"type":"string","format":"date-time"},"endTime":{"type":"string","format":"date-time"}}},
  "RankingResponse": {"type":"object","required":["rankings"],"properties":{"rankedAt":{"type":["string","null"],"format":"date-time"},"rankings":{"type":"array","items":{"$ref":"#/components/schemas/RankingItem"}}}},
  "RankingItem": {"type":"object","required":["rank","symbol","currency","price","tradingVolume","tradingAmount"],"properties":{"rank":{"type":"integer"},"symbol":{"type":"string"},"currency":{"$ref":"#/components/schemas/Currency"},"price":{"$ref":"#/components/schemas/RankingPrice"},"tradingVolume":{"type":"string","format":"decimal","maxLength":30},"tradingAmount":{"type":"string","format":"decimal","maxLength":30}}},
  "RankingPrice": {"type":"object","required":["lastPrice","basePrice"],"properties":{"lastPrice":{"type":"string","format":"decimal","maxLength":30},"basePrice":{"type":"string","format":"decimal","maxLength":30},"changeRate":{"type":["string","null"],"format":"decimal","maxLength":30}}},
  "MarketIndicatorPriceResponse": {"type":"object","required":["symbol","lastPrice"],"properties":{"symbol":{"type":"string"},"timestamp":{"type":["string","null"],"format":"date-time"},"lastPrice":{"type":"string","format":"decimal","maxLength":30}}},
  "MarketIndicatorCandlePageResponse": {"type":"object","required":["candles"],"properties":{"candles":{"type":"array","items":{"$ref":"#/components/schemas/MarketIndicatorCandle"}},"nextBefore":{"type":["string","null"],"format":"date-time"}}},
  "MarketIndicatorCandle": {"type":"object","required":["timestamp","openPrice","highPrice","lowPrice","closePrice","volume"],"properties":{"timestamp":{"type":"string","format":"date-time"},"openPrice":{"type":"string","format":"decimal","maxLength":30},"highPrice":{"type":"string","format":"decimal","maxLength":30},"lowPrice":{"type":"string","format":"decimal","maxLength":30},"closePrice":{"type":"string","format":"decimal","maxLength":30},"volume":{"type":"string","format":"decimal","maxLength":30}}},
  "InvestorTradingResponse": {"type":"object","required":["records"],"properties":{"nextUntil":{"type":["string","null"],"format":"date"},"records":{"type":"array","items":{"$ref":"#/components/schemas/InvestorTradingRecord"}}}},
  "InvestorTradingRecord": {"type":"object","required":["date","updatedAt","individual","foreigner","institution","otherCorporation"],"properties":{"date":{"type":"string","format":"date"},"updatedAt":{"type":"string","format":"date-time"},"individual":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"foreigner":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"institution":{"allOf":[{"$ref":"#/components/schemas/InstitutionTradingAmount"}]},"otherCorporation":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]}}},
  "InvestorTradingAmount": {"type":"object","required":["buyAmount","sellAmount"],"properties":{"buyAmount":{"type":"string","format":"decimal","maxLength":30},"sellAmount":{"type":"string","format":"decimal","maxLength":30}}},
  "InstitutionTradingAmount": {"type":"object","required":["buyAmount","sellAmount","breakdown"],"properties":{"buyAmount":{"type":"string","format":"decimal","maxLength":30},"sellAmount":{"type":"string","format":"decimal","maxLength":30},"breakdown":{"$ref":"#/components/schemas/InstitutionTradingBreakdown"}}},
  "InstitutionTradingBreakdown": {"type":"object","required":["financialInvestment","insurance","trust","privateEquityFund","bank","otherFinancialInstitution","pensionFund"],"properties":{"financialInvestment":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"insurance":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"trust":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"privateEquityFund":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"bank":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"otherFinancialInstitution":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]},"pensionFund":{"allOf":[{"$ref":"#/components/schemas/InvestorTradingAmount"}]}}},
  "SectorsResponse": {"type":"object","required":["sectors"],"properties":{"sectors":{"type":"array","items":{"$ref":"#/components/schemas/Sector"}}}},
  "Sector": {"type":"object","required":["sectorId","name","depth","parentSectorId"],"properties":{"sectorId":{"type":"string"},"name":{"type":"string"},"depth":{"type":"integer"},"parentSectorId":{"type":["string","null"]}}},
  "SectorDetailResponse": {"type":"object","required":["sectorId","name","depth","parentSectorId","summary","performance"],"properties":{"sectorId":{"type":"string"},"name":{"type":"string"},"depth":{"type":"integer"},"parentSectorId":{"type":["string","null"]},"summary":{"type":["string","null"]},"performance":{"$ref":"#/components/schemas/SectorPerformance"}}},
  "SectorPerformance": {"type":"object","required":["changeRates"],"properties":{"changeRates":{"type":"array","items":{"$ref":"#/components/schemas/SectorChangeRate"}}}},
  "SectorChangeRate": {"type":"object","required":["duration","changeRate"],"properties":{"duration":{"type":"string"},"changeRate":{"type":["string","null"],"format":"decimal","maxLength":30}}},
  "SectorStocksResponse": {"type":"object","required":["stocks"],"properties":{"stocks":{"type":"array","items":{"$ref":"#/components/schemas/SectorStock"}}}},
  "SectorStock": {"type":"object","required":["symbol","name","volume","tradingAmount","marketCapitalization","currency"],"properties":{"symbol":{"type":"string"},"name":{"type":"string"},"volume":{"type":["string","null"],"format":"decimal","maxLength":30},"tradingAmount":{"type":["string","null"],"format":"decimal","maxLength":30},"marketCapitalization":{"type":["string","null"],"format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "SectorEtfsResponse": {"type":"object","required":["etfs"],"properties":{"etfs":{"type":"array","items":{"$ref":"#/components/schemas/SectorEtf"}}}},
  "SectorEtf": {"type":"object","required":["symbol","name"],"properties":{"symbol":{"type":"string"},"name":{"type":"string"}}},
  "SectorRankingResponse": {"type":"object","required":["rankings"],"properties":{"rankings":{"type":"array","items":{"$ref":"#/components/schemas/SectorRankingItem"}}}},
  "SectorRankingItem": {"type":"object","required":["rank","sectorId","name","changeRate","tradingAmount","marketCapitalization","currency"],"properties":{"rank":{"type":"integer"},"sectorId":{"type":"string"},"name":{"type":"string"},"changeRate":{"type":["string","null"],"format":"decimal","maxLength":30},"tradingAmount":{"type":["string","null"],"format":"decimal","maxLength":30},"marketCapitalization":{"type":["string","null"],"format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"}}},
  "Account": {"type":"object","required":["accountNo","accountSeq","accountType"],"properties":{"accountNo":{"type":"string"},"accountSeq":{"type":"integer","format":"int64"},"accountType":{"type":"string"}}},
  "HoldingsOverview": {"type":"object","required":["totalPurchaseAmount","marketValue","profitLoss","dailyProfitLoss","items"],"properties":{"totalPurchaseAmount":{"allOf":[{"$ref":"#/components/schemas/Price"}]},"marketValue":{"$ref":"#/components/schemas/OverviewMarketValue"},"profitLoss":{"$ref":"#/components/schemas/OverviewProfitLoss"},"dailyProfitLoss":{"$ref":"#/components/schemas/OverviewDailyProfitLoss"},"items":{"type":"array","items":{"$ref":"#/components/schemas/HoldingsItem"}}}},
  "HoldingsItem": {"type":"object","required":["symbol","name","marketCountry","currency","quantity","lastPrice","averagePurchasePrice","marketValue","profitLoss","dailyProfitLoss","cost"],"properties":{"symbol":{"type":"string"},"name":{"type":"string"},"marketCountry":{"$ref":"#/components/schemas/MarketCountry"},"currency":{"$ref":"#/components/schemas/Currency"},"quantity":{"type":"string","format":"decimal","maxLength":30},"lastPrice":{"type":"string","format":"decimal","maxLength":30},"averagePurchasePrice":{"type":"string","format":"decimal","maxLength":30},"marketValue":{"$ref":"#/components/schemas/MarketValue"},"profitLoss":{"$ref":"#/components/schemas/ProfitLoss"},"dailyProfitLoss":{"$ref":"#/components/schemas/DailyProfitLoss"},"cost":{"$ref":"#/components/schemas/Cost"}}},
  "Price": {"type":"object","required":["krw"],"properties":{"krw":{"type":"string","format":"decimal","maxLength":30},"usd":{"type":["string","null"],"format":"decimal","maxLength":30}}},
  "OverviewMarketValue": {"type":"object","required":["amount","amountAfterCost"],"properties":{"amount":{"allOf":[{"$ref":"#/components/schemas/Price"}]},"amountAfterCost":{"allOf":[{"$ref":"#/components/schemas/Price"}]}}},
  "OverviewProfitLoss": {"type":"object","required":["amount","amountAfterCost","rate","rateAfterCost"],"properties":{"amount":{"allOf":[{"$ref":"#/components/schemas/Price"}]},"amountAfterCost":{"allOf":[{"$ref":"#/components/schemas/Price"}]},"rate":{"type":"string","format":"decimal","maxLength":30},"rateAfterCost":{"type":"string","format":"decimal","maxLength":30}}},
  "OverviewDailyProfitLoss": {"type":"object","required":["amount","rate"],"properties":{"amount":{"allOf":[{"$ref":"#/components/schemas/Price"}]},"rate":{"type":"string","format":"decimal","maxLength":30}}},
  "MarketValue": {"type":"object","required":["purchaseAmount","amount","amountAfterCost"],"properties":{"purchaseAmount":{"type":"string","format":"decimal","maxLength":30},"amount":{"type":"string","format":"decimal","maxLength":30},"amountAfterCost":{"type":"string","format":"decimal","maxLength":30}}},
  "ProfitLoss": {"type":"object","required":["amount","amountAfterCost","rate","rateAfterCost"],"properties":{"amount":{"type":"string","format":"decimal","maxLength":30},"amountAfterCost":{"type":"string","format":"decimal","maxLength":30},"rate":{"type":"string","format":"decimal","maxLength":30},"rateAfterCost":{"type":"string","format":"decimal","maxLength":30}}},
  "DailyProfitLoss": {"type":"object","required":["amount","rate"],"properties":{"amount":{"type":"string","format":"decimal","maxLength":30},"rate":{"type":"string","format":"decimal","maxLength":30}}},
  "Cost": {"type":"object","required":["commission"],"properties":{"commission":{"type":"string","format":"decimal","maxLength":30},"tax":{"type":["string","null"],"format":"decimal","maxLength":30}}},
  "OrderCreateRequest": {"oneOf":[{"type":"object","required":["symbol","side","orderType","quantity"],"properties":{"clientOrderId":{"type":"string","maxLength":36,"pattern":"^[a-zA-Z0-9\\-_]+$"},"symbol":{"type":"string"},"side":{"type":"string"},"orderType":{"type":"string"},"timeInForce":{"type":"string"},"quantity":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"price":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"confirmHighValueOrder":{"type":"boolean"}}},{"type":"object","required":["symbol","side","orderType","orderAmount"],"properties":{"clientOrderId":{"type":"string","maxLength":36,"pattern":"^[a-zA-Z0-9\\-_]+$"},"symbol":{"type":"string"},"side":{"type":"string"},"orderType":{"type":"string"},"orderAmount":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"confirmHighValueOrder":{"type":"boolean"}}}]},
  "OrderModifyRequest": {"type":"object","required":["orderType"],"properties":{"orderType":{"type":"string"},"quantity":{"type":"string","format":"decimal","pattern":"^\\d+$","maxLength":30},"price":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"confirmHighValueOrder":{"type":"boolean"}}},
  "OrderResponse": {"type":"object","required":["orderId"],"properties":{"orderId":{"type":"string"},"clientOrderId":{"type":["string","null"]}}},
  "OrderOperationResponse": {"type":"object","required":["orderId"],"properties":{"orderId":{"type":"string"}}},
  "ConditionalOrderCreateRequest": {"type":"object","required":["symbol","type","quantity","orderType","expireDate","first"],"properties":{"symbol":{"type":"string"},"type":{"type":"string"},"quantity":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"orderType":{"type":"string"},"clientOrderId":{"type":"string","maxLength":36,"pattern":"^[a-zA-Z0-9\\-_]+$"},"expireDate":{"type":"string","format":"date"},"first":{"allOf":[{"$ref":"#/components/schemas/ConditionRequest"}]},"second":{"allOf":[{"$ref":"#/components/schemas/ConditionRequest"}],"nullable":true},"confirmHighValueOrder":{"type":"boolean"}}},
  "ConditionalOrderModifyRequest": {"type":"object","required":["type","quantity","orderType","expireDate","first"],"properties":{"type":{"type":"string"},"quantity":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"orderType":{"type":"string"},"expireDate":{"type":"string","format":"date"},"first":{"allOf":[{"$ref":"#/components/schemas/ConditionRequest"}]},"second":{"allOf":[{"$ref":"#/components/schemas/ConditionRequest"}],"nullable":true},"confirmHighValueOrder":{"type":"boolean"}}},
  "ConditionRequest": {"type":"object","required":["orderSide","triggerPrice"],"properties":{"orderSide":{"type":"string"},"triggerPrice":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30},"orderPrice":{"type":"string","format":"decimal","pattern":"^\\d+(\\.\\d+)?$","maxLength":30}}},
  "ConditionalOrderResponse": {"type":"object","required":["conditionalOrderId"],"properties":{"conditionalOrderId":{"type":"string"}}},
  "PaginatedConditionalOrderResponse": {"type":"object","required":["conditionalOrders","hasNext"],"properties":{"conditionalOrders":{"type":"array","items":{"$ref":"#/components/schemas/ConditionalOrderDetailResponse"}},"nextCursor":{"type":["string","null"]},"hasNext":{"type":"boolean"}}},
  "ConditionalOrderDetailResponse": {"type":"object","required":["conditionalOrderId","type","status","symbol","market","quantity","orderType","first","createdAt"],"properties":{"conditionalOrderId":{"type":"string"},"type":{"type":"string"},"status":{"type":"string"},"symbol":{"type":"string"},"market":{"type":"string"},"quantity":{"type":"string","format":"decimal"},"orderType":{"type":"string"},"expireDate":{"type":"string","format":"date"},"first":{"allOf":[{"$ref":"#/components/schemas/ConditionalOrderCondition"}]},"second":{"allOf":[{"$ref":"#/components/schemas/ConditionalOrderCondition"}],"nullable":true},"createdAt":{"type":"string","format":"date-time"}}},
  "ConditionalOrderCondition": {"type":"object","required":["type","status","orderSide"],"properties":{"type":{"type":"string"},"status":{"type":"string"},"orderSide":{"type":"string"},"triggerPrice":{"type":["string","null"],"format":"decimal"},"targetProfitRate":{"type":["string","null"],"format":"decimal"},"orderPrice":{"type":["string","null"],"format":"decimal"},"triggeredOrderId":{"type":["string","null"]}}},
  "PaginatedOrderResponse": {"type":"object","required":["orders","nextCursor","hasNext"],"properties":{"orders":{"type":"array","items":{"$ref":"#/components/schemas/Order"}},"nextCursor":{"type":["string","null"]},"hasNext":{"type":"boolean"}}},
  "Order": {"type":"object","required":["orderId","symbol","side","orderType","timeInForce","status","quantity","currency","orderedAt","execution"],"properties":{"orderId":{"type":"string"},"symbol":{"type":"string"},"side":{"type":"string"},"orderType":{"type":"string"},"timeInForce":{"type":"string"},"status":{"$ref":"#/components/schemas/OrderStatus"},"price":{"type":["string","null"],"format":"decimal","maxLength":30},"quantity":{"type":"string","format":"decimal","maxLength":30},"orderAmount":{"type":["string","null"],"format":"decimal","maxLength":30},"currency":{"$ref":"#/components/schemas/Currency"},"orderedAt":{"type":"string","format":"date-time"},"canceledAt":{"type":["string","null"],"format":"date-time"},"execution":{"type":"object","allOf":[{"$ref":"#/components/schemas/OrderExecution"}]}}},
  "OrderExecution": {"type":"object","required":["filledQuantity","averageFilledPrice","filledAmount","commission","tax","filledAt","settlementDate"],"properties":{"filledQuantity":{"type":"string","format":"decimal","maxLength":30},"averageFilledPrice":{"type":["string","null"],"format":"decimal","maxLength":30},"filledAmount":{"type":["string","null"],"format":"decimal","maxLength":30},"commission":{"type":["string","null"],"format":"decimal","maxLength":30},"tax":{"type":["string","null"],"format":"decimal","maxLength":30},"filledAt":{"type":["string","null"],"format":"date-time"},"settlementDate":{"type":["string","null"],"format":"date"}}},
  "OrderStatus": {"type":"string"},
  "BuyingPowerResponse": {"type":"object","required":["currency","cashBuyingPower"],"properties":{"currency":{"$ref":"#/components/schemas/Currency"},"cashBuyingPower":{"type":"string","format":"decimal","maxLength":30}}},
  "SellableQuantityResponse": {"type":"object","required":["sellableQuantity"],"properties":{"sellableQuantity":{"type":"string","format":"decimal","maxLength":30}}},
  "Commission": {"type":"object","required":["marketCountry","commissionRate"],"properties":{"marketCountry":{"$ref":"#/components/schemas/MarketCountry"},"commissionRate":{"type":"string","format":"decimal","maxLength":30},"startDate":{"type":["string","null"],"format":"date"},"endDate":{"type":["string","null"],"format":"date"}}},
  "ConditionalOrderCreateResponse": {"type":"object","required":["conditionalOrderId"],"properties":{"conditionalOrderId":{"type":"string"},"clientOrderId":{"type":["string","null"]}}},
};

export type ApiResponse = { "result": unknown };
export type ErrorResponse = { "error": ApiError };
export type ApiError = { "requestId": string; "code": string; "message": string; "data"?: {  } | null };
export type Currency = string;
export type MarketCountry = string;
export type OAuth2TokenRequest = { "grant_type": string; "client_id": string; "client_secret": string };
export type OAuth2TokenResponse = { "access_token": string; "token_type": string; "expires_in": number | string };
export type OAuth2ErrorResponse = { "error": string; "error_description"?: string; "error_uri"?: string };
export type OrderbookEntry = { "price": string; "volume": string };
export type OrderbookResponse = { "timestamp"?: string | null; "currency": Currency; "asks": (OrderbookEntry)[]; "bids": (OrderbookEntry)[] };
export type PriceResponse = { "symbol": string; "timestamp"?: string | null; "lastPrice": string; "currency": Currency };
export type Trade = { "price": string; "volume": string; "timestamp": string; "currency": Currency };
export type PriceLimitResponse = { "timestamp": string; "upperLimitPrice"?: string | null; "lowerLimitPrice"?: string | null; "currency": Currency };
export type CandlePageResponse = { "candles": (Candle)[]; "nextBefore"?: string | null };
export type Candle = { "timestamp": string; "openPrice": string; "highPrice": string; "lowPrice": string; "closePrice": string; "volume": string; "currency": Currency };
export type StockInfo = { "symbol": string; "name": string; "englishName": string; "isinCode": string; "market": string; "securityType": string; "isCommonShare": boolean; "status": string; "currency": Currency; "listDate"?: string | null; "delistDate"?: string | null; "sharesOutstanding": string; "leverageFactor"?: string | null; "koreanMarketDetail"?: (KrMarketDetail | null) };
export type KrMarketDetail = { "liquidationTrading": boolean; "nxtSupported": boolean; "krxTradingSuspended": boolean; "nxtTradingSuspended"?: boolean | null };
export type StockWarning = { "warningType": string; "exchange"?: string | null; "startDate"?: string | null; "endDate"?: string | null };
export type ListedStock = { "symbol": string; "name": string; "securityType": string; "isCommonShare": boolean; "isinCode": string };
export type StockInvestorTradingResponse = { "nextUntil"?: string | null; "records": (StockInvestorTradingRecord)[] };
export type StockInvestorTradingRecord = { "date": string; "updatedAt": string; "individual"?: (InvestorTradingVolume | null); "foreigner": (InvestorTradingVolume); "institution": (StockInstitutionTradingVolume); "otherCorporation"?: (InvestorTradingVolume | null); "foreignerHolding"?: (ForeignerHolding | null); "cfd"?: (CfdBalance | null) };
export type InvestorTradingVolume = { "buyVolume": string; "sellVolume": string; "netBuyVolume": string };
export type StockInstitutionTradingVolume = { "buyVolume": string; "sellVolume": string; "netBuyVolume": string; "breakdown"?: (StockInstitutionTradingBreakdown | null) };
export type StockInstitutionTradingBreakdown = { "financialInvestment": (InvestorTradingVolume); "insurance": (InvestorTradingVolume); "trust": (InvestorTradingVolume); "privateEquityFund": (InvestorTradingVolume); "bank": (InvestorTradingVolume); "otherFinancialInstitution": (InvestorTradingVolume); "pensionFund": (InvestorTradingVolume) };
export type ForeignerHolding = { "holdingQuantity": string; "limitQuantity": string; "holdingRate": string };
export type CfdBalance = { "buyBalanceQuantity": string; "buyBalanceRate": string; "sellBalanceQuantity": string; "sellBalanceRate": string };
export type ProgramTradesResponse = { "nextUntil"?: string | null; "records": (ProgramTradeRecord)[] };
export type ProgramTradeRecord = { "date": string; "arbitrage": (ProgramTradingVolume); "nonArbitrage": (ProgramTradingVolume) };
export type ProgramTradingVolume = { "buyVolume": string; "sellVolume": string; "netBuyVolume": string };
export type ShortSellingResponse = { "nextUntil"?: string | null; "records": (ShortSellingRecord)[] };
export type ShortSellingRecord = { "date": string; "updatedAt": string; "shortSellingVolume": string; "shortSellingAmount": string; "shortSellingVolumeRate"?: string | null; "shortSellingAmountRate"?: string | null };
export type CreditTradesResponse = { "nextUntil"?: string | null; "records": (CreditTradeRecord)[] };
export type CreditTradeRecord = { "date": string; "updatedAt": string; "marginLoan"?: (CreditTradeDetail | null); "stockLoan"?: (CreditTradeDetail | null) };
export type CreditTradeDetail = { "newQuantity": string; "returnQuantity": string; "balanceQuantity": string; "balanceRate": string; "tradingRate": string };
export type SecuritiesLendingResponse = { "nextUntil"?: string | null; "records": (SecuritiesLendingRecord)[] };
export type SecuritiesLendingRecord = { "date": string; "updatedAt": string; "executionQuantity": string; "repaymentQuantity": string; "balanceQuantity": string; "balanceAmount": string };
export type ExchangeRateResponse = { "baseCurrency": Currency; "quoteCurrency": Currency; "rate": string; "midRate": string; "basisPoint": string; "rateChangeType": string; "validFrom": string; "validUntil": string };
export type KrMarketCalendarResponse = { "today": KrMarketDay; "previousBusinessDay": KrMarketDay; "nextBusinessDay": KrMarketDay };
export type KrMarketDay = { "date": string; "integrated"?: (IntegratedHour | null) };
export type IntegratedHour = { "preMarket"?: (PreMarketSession | null); "regularMarket"?: (RegularMarketSession | null); "afterMarket"?: (AfterMarketSession | null) };
export type PreMarketSession = { "startTime": string; "singlePriceAuctionStartTime"?: (string | null); "endTime": string };
export type RegularMarketSession = { "startTime": string; "singlePriceAuctionStartTime"?: (string | null); "endTime": string };
export type AfterMarketSession = { "startTime": string; "singlePriceAuctionEndTime"?: (string | null); "endTime": string };
export type UsMarketCalendarResponse = { "today": UsMarketDay; "previousBusinessDay": UsMarketDay; "nextBusinessDay": UsMarketDay };
export type UsMarketDay = { "date": string; "dayMarket"?: (UsDayMarketSession | null); "preMarket"?: (UsPreMarketSession | null); "regularMarket"?: (UsRegularMarketSession | null); "afterMarket"?: (UsAfterMarketSession | null) };
export type UsDayMarketSession = { "startTime": string; "endTime": string };
export type UsPreMarketSession = { "startTime": string; "endTime": string };
export type UsRegularMarketSession = { "startTime": string; "endTime": string };
export type UsAfterMarketSession = { "startTime": string; "endTime": string };
export type RankingResponse = { "rankedAt"?: string | null; "rankings": (RankingItem)[] };
export type RankingItem = { "rank": number; "symbol": string; "currency": Currency; "price": RankingPrice; "tradingVolume": string; "tradingAmount": string };
export type RankingPrice = { "lastPrice": string; "basePrice": string; "changeRate"?: string | null };
export type MarketIndicatorPriceResponse = { "symbol": string; "timestamp"?: string | null; "lastPrice": string };
export type MarketIndicatorCandlePageResponse = { "candles": (MarketIndicatorCandle)[]; "nextBefore"?: string | null };
export type MarketIndicatorCandle = { "timestamp": string; "openPrice": string; "highPrice": string; "lowPrice": string; "closePrice": string; "volume": string };
export type InvestorTradingResponse = { "nextUntil"?: string | null; "records": (InvestorTradingRecord)[] };
export type InvestorTradingRecord = { "date": string; "updatedAt": string; "individual": (InvestorTradingAmount); "foreigner": (InvestorTradingAmount); "institution": (InstitutionTradingAmount); "otherCorporation": (InvestorTradingAmount) };
export type InvestorTradingAmount = { "buyAmount": string; "sellAmount": string };
export type InstitutionTradingAmount = { "buyAmount": string; "sellAmount": string; "breakdown": InstitutionTradingBreakdown };
export type InstitutionTradingBreakdown = { "financialInvestment": (InvestorTradingAmount); "insurance": (InvestorTradingAmount); "trust": (InvestorTradingAmount); "privateEquityFund": (InvestorTradingAmount); "bank": (InvestorTradingAmount); "otherFinancialInstitution": (InvestorTradingAmount); "pensionFund": (InvestorTradingAmount) };
export type SectorsResponse = { "sectors": (Sector)[] };
export type Sector = { "sectorId": string; "name": string; "depth": number; "parentSectorId": string | null };
export type SectorDetailResponse = { "sectorId": string; "name": string; "depth": number; "parentSectorId": string | null; "summary": string | null; "performance": SectorPerformance };
export type SectorPerformance = { "changeRates": (SectorChangeRate)[] };
export type SectorChangeRate = { "duration": string; "changeRate": string | null };
export type SectorStocksResponse = { "stocks": (SectorStock)[] };
export type SectorStock = { "symbol": string; "name": string; "volume": string | null; "tradingAmount": string | null; "marketCapitalization": string | null; "currency": Currency };
export type SectorEtfsResponse = { "etfs": (SectorEtf)[] };
export type SectorEtf = { "symbol": string; "name": string };
export type SectorRankingResponse = { "rankings": (SectorRankingItem)[] };
export type SectorRankingItem = { "rank": number; "sectorId": string; "name": string; "changeRate": string | null; "tradingAmount": string | null; "marketCapitalization": string | null; "currency": Currency };
export type Account = { "accountNo": string; "accountSeq": number | string; "accountType": string };
export type HoldingsOverview = { "totalPurchaseAmount": (Price); "marketValue": OverviewMarketValue; "profitLoss": OverviewProfitLoss; "dailyProfitLoss": OverviewDailyProfitLoss; "items": (HoldingsItem)[] };
export type HoldingsItem = { "symbol": string; "name": string; "marketCountry": MarketCountry; "currency": Currency; "quantity": string; "lastPrice": string; "averagePurchasePrice": string; "marketValue": MarketValue; "profitLoss": ProfitLoss; "dailyProfitLoss": DailyProfitLoss; "cost": Cost };
export type Price = { "krw": string; "usd"?: string | null };
export type OverviewMarketValue = { "amount": (Price); "amountAfterCost": (Price) };
export type OverviewProfitLoss = { "amount": (Price); "amountAfterCost": (Price); "rate": string; "rateAfterCost": string };
export type OverviewDailyProfitLoss = { "amount": (Price); "rate": string };
export type MarketValue = { "purchaseAmount": string; "amount": string; "amountAfterCost": string };
export type ProfitLoss = { "amount": string; "amountAfterCost": string; "rate": string; "rateAfterCost": string };
export type DailyProfitLoss = { "amount": string; "rate": string };
export type Cost = { "commission": string; "tax"?: string | null };
export type OrderCreateRequest = ({ "clientOrderId"?: string; "symbol": string; "side": string; "orderType": string; "timeInForce"?: string; "quantity": string; "price"?: string; "confirmHighValueOrder"?: boolean } | { "clientOrderId"?: string; "symbol": string; "side": string; "orderType": string; "orderAmount": string; "confirmHighValueOrder"?: boolean });
export type OrderModifyRequest = { "orderType": string; "quantity"?: string; "price"?: string; "confirmHighValueOrder"?: boolean };
export type OrderResponse = { "orderId": string; "clientOrderId"?: string | null };
export type OrderOperationResponse = { "orderId": string };
export type ConditionalOrderCreateRequest = { "symbol": string; "type": string; "quantity": string; "orderType": string; "clientOrderId"?: string; "expireDate": string; "first": (ConditionRequest); "second"?: (ConditionRequest) | null; "confirmHighValueOrder"?: boolean };
export type ConditionalOrderModifyRequest = { "type": string; "quantity": string; "orderType": string; "expireDate": string; "first": (ConditionRequest); "second"?: (ConditionRequest) | null; "confirmHighValueOrder"?: boolean };
export type ConditionRequest = { "orderSide": string; "triggerPrice": string; "orderPrice"?: string };
export type ConditionalOrderResponse = { "conditionalOrderId": string };
export type PaginatedConditionalOrderResponse = { "conditionalOrders": (ConditionalOrderDetailResponse)[]; "nextCursor"?: string | null; "hasNext": boolean };
export type ConditionalOrderDetailResponse = { "conditionalOrderId": string; "type": string; "status": string; "symbol": string; "market": string; "quantity": string; "orderType": string; "expireDate"?: string; "first": (ConditionalOrderCondition); "second"?: (ConditionalOrderCondition) | null; "createdAt": string };
export type ConditionalOrderCondition = { "type": string; "status": string; "orderSide": string; "triggerPrice"?: string | null; "targetProfitRate"?: string | null; "orderPrice"?: string | null; "triggeredOrderId"?: string | null };
export type PaginatedOrderResponse = { "orders": (Order)[]; "nextCursor": string | null; "hasNext": boolean };
export type Order = { "orderId": string; "symbol": string; "side": string; "orderType": string; "timeInForce": string; "status": OrderStatus; "price"?: string | null; "quantity": string; "orderAmount"?: string | null; "currency": Currency; "orderedAt": string; "canceledAt"?: string | null; "execution": (OrderExecution) };
export type OrderExecution = { "filledQuantity": string; "averageFilledPrice": string | null; "filledAmount": string | null; "commission": string | null; "tax": string | null; "filledAt": string | null; "settlementDate": string | null };
export type OrderStatus = string;
export type BuyingPowerResponse = { "currency": Currency; "cashBuyingPower": string };
export type SellableQuantityResponse = { "sellableQuantity": string };
export type Commission = { "marketCountry": MarketCountry; "commissionRate": string; "startDate"?: string | null; "endDate"?: string | null };
export type ConditionalOrderCreateResponse = { "conditionalOrderId": string; "clientOrderId"?: string | null };

export const CURRENT_OPERATIONS = new Set(["issueOAuth2Token", "getAccounts", "getPrices", "getStocks", "getHoldings", "getBuyingPower", "getSellableQuantity", "getOrders"]);
export function matchesOperation(operation: Operation, method: string, path: string): boolean {
  const template = operation.path.split("/");
  const segments = path.split("/");
  return operation.method === method && template.length === segments.length && template.every((part, i) => part.startsWith("{") ? Boolean(segments[i]) : part === segments[i]);
}
export function operationFor(method: string, path: string): Operation {
  const operation = OPERATIONS.find(item => matchesOperation(item, method, path));
  if (!operation) throw new TossinvestError("TOSSINVEST_INVALID_INPUT");
  return operation;
}
export function parseApiResponse(raw: string, _operation: Operation, _status: number): any {
  return JSON.parse(raw);
}
